### ISSUE TITLE
Error when enabling on a sub-project

### ISSUE THREAD

**Issue by mauhiz** [CSUG/sbt-one-log#5]
SBT 0.13.7 with cached resolution enabled

The error is like this: 
> java.io.FileNotFoundException: C:\projects\my_project\my_sub_project\target\resolution-cache\reports\com.me.my_sub_project_2.11-compile.xml
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at scala.io.Source$.fromFile(Source.scala:90)
        at scala.io.Source$.fromFile(Source.scala:75)
        at scala.io.Source$.fromFile(Source.scala:53)
        at com.zavakid.sbt.IvyGraphMLDependencies$.buildDoc(Util.scala:141)
        at com.zavakid.sbt.IvyGraphMLDependencies$.graph(Util.scala:62)
        at com.zavakid.sbt.SbtOneLog$$anonfun$projectSettings$7.apply(SbtOneLog.scala:111)
        at com.zavakid.sbt.SbtOneLog$$anonfun$projectSettings$7.apply(SbtOneLog.scala:111)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)

**Comment by zavakid** [comment]
can't find the report file `\com.me.my_sub_project_2.11-compile.xml` means that the update gen a wrong report file path.
I've test with sbt 0.13.7 and scala 2.11.5 with sub project, and can't repeat your problem.
