### ISSUE TITLE
scala-logging error with scala 2.11 

### ISSUE THREAD

**Issue by zavakid** [CSUG/sbt-one-log#8]
with sbt scripted : 

[info] [error] (*:check) libraryDependencies [com.typesafe.scala-logging:scala-logging-api_2.11:2.1.2] error!
[info] [error] Total time: 0 s, completed 2015-3-6 23:45:03
[error] x sbt-one-log / simple_0.13.7
[error]    {line 1}  Command failed: check failed
java.lang.RuntimeException: Failed tests:
	sbt-one-log / multi_0.13.7
	sbt-one-log / simple_0.13.7

	at scala.sys.package$.error(package.scala:27)
	at sbt.test.ScriptedTests$.runAll(ScriptedTests.scala:119)
	at sbt.test.ScriptedTests$.run(ScriptedTests.scala:114)
	at sbt.test.ScriptedTests$.run(ScriptedTests.scala:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$3$$anonfun$apply$4.apply(ScriptedPlugin.scala:61)
	at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$3$$anonfun$apply$4.apply(ScriptedPlugin.scala:57)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)

**Comment by zavakid** [comment]
for scala 2.11, use `"com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"`

**Comment by jpzk** [comment]
My article about cross version use of scala logging could be useful for people using scala-logging: https://www.madewithtea.com/cross-version-scala-logging-with-sbt.html
